production: 
  app: coupe-baguette
  stack: cedar
  tag: production/*
  config:
    BUNDLE_WITHOUT: "development:test"
    TZ: Asia/Tokyo

staging:
  app: coupe-baguette-staging
  stack: cedar
  config: &default
    BUNDLE_WITHOUT: "development:test"
    RACK_ENV: staging
    RAILS_ENV: staging
    TZ: Asia/Tokyo
